version: '2.0'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./conf:/etc/nginx/conf.d
    links:
      - uwsgi
    depends_on:
      - uwsgi

  uwsgi:
    build: uwsgi
    ports:
      - 8080:8080
    volumes:
      - ./ky-storm:/var/app/ky-storm
    environment:
      - MYSQL_ROOT_PASSWORD = root
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mysql
    expose:
      - 3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD = root