version: '2.0'
services:
#  nginx:
#    image: nginx
#    ports:
#      - 80:80
#    volumes:
#      - ./conf:/etc/nginx/conf.d
#    links:
#      - uwsgi
#    depends_on:
#      - uwsgi
#      - mysql
#    volumes_from:
#      - uwsgi


  uwsgi:
    build: uwsgi
    ports:
      - 8080:8080
    volumes:
      - ./uwsgi/app/ky-storm:/var/app/ky-storm
    environment:
      MYSQL_ROOT_PASSWORD: root
    links:
      - mysql
    command: /wait_for_mysql.sh

  mysql:
    build: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog