version: '2'
services:
  uwsgi:
    build: uwsgi
    ports:
      - 8080:8080
    volumes:
      - ./uwsgi/app/ky-storm:/var/app/ky-storm
    environment:
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - mysql
    links:
      - mysql:db

  mysql:
    build: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./conf:/etc/nginx/conf.d
    depends_on:
      - uwsgi
    volumes_from:
      - uwsgi:ro
    links:
      - uwsgi